### ISSUE TITLE
Git tags missing?

### ISSUE THREAD

**Issue by hartwork** [EdSchouten/hidesvn#1]
Hi Ed,

still using this tool every day as part of my alias setup:
```
# alias | fgrep hidesvn
alias fgrep='hidesvn fgrep --color=auto -I'
alias find='hidesvn find'
alias grep='hidesvn grep --color=auto -I'
```
In relation to https://github.com/vfeskov/WinABeer/issues/23 I noticed now that there are no Git tags in here. On purpose?

Best, Sebastian

**Comment by EdSchouten** [comment]
Hi Sebastian! How are you doing? \o/

I suspect the tags that were in this repository got lost over time. This code used to be stored in SVN. I guess I didn't preserve the tags during the migration to Git. Let's see whether I can recreate the tags based on the source tarball contents.

**Comment by EdSchouten** [comment]
Fixed! Tags have been recreated.

**Comment by hartwork** [comment]
Cool, thanks!
